### ISSUE TITLE
Can't create vehicle

### ISSUE THREAD

**Issue by drac** [cad/vehicle-tracker-api#16] opened 2017-08-20 11:40 UTC
According to API documentation (version 1.1.4) you should be able to create a vehicle by POST'ing only `plate_id` and `type` data but when you try this It returns a **bad request (400)** error.

**Comment by cad** [comment] 2017-08-23 21:00
I've verified that this endpoint **creates** and **returns** a vehicle by POSTing only `plate_id` and `type` (as documented). You can see the session below.

Request:
```
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: Bearer 7217d04f-02e1-4940-9ce7-9829c7e7b318' -d '{ \ 
   "plate_id": "33AAA", \ 
   "type": "SCHOOL-BUS" \ 
 }' 'https://api.vehicles.neu.edu.tr/vehicle/'
```

Response:
```
{
  "updated_at": "2017-08-23T23:53:37.762152229+03:00",
  "plate_id": "33AAA",
  "agent": {
    "uuid": "5f89316c-20ed-11e7-93ae-92361f002671",
    "updated_at": "2017-08-23T23:53:37.754413886+03:00",
    "label": "",
    "lat": "3513.4433",
    "lon": "03319.4641",
    "gps_ts": "120209.000"
  },
  "groups": null,
  "type": "SCHOOL-BUS"
}
```

Since the endpoint is working as documented, I'm closing this.

**Comment by drac** [comment] 2017-08-25 09:31
I've re-verified that you can not create a vehicle only by POSTing `plate_id` and `type` (as documented in v1.1.5) unless you already have at least one **agent** created before.

**When you try to create a vehicle without any agents on the system by posting only the required parameters (`plate_id` and `type`);**

```
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: Bearer b1d02b5e-e077-4328-8d1f-e17d7a2530ac' -d '{ \ 
   "plate_id": "CC555", \ 
   "type": "SCHOOL-BUS" \ 
 }' 'http://localhost:5004/vehicle/'
```

Response is;

```
{
  "message": "Not-Found: <Agent> "
}
```


**Let's try to create the same vehicle with same parameters after creating an agent with `uuid = "testagent1"`**

```
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: Bearer b1d02b5e-e077-4328-8d1f-e17d7a2530ac' -d '{ \ 
   "plate_id": "CC555", \ 
   "type": "SCHOOL-BUS" \ 
 }' 'http://localhost:5004/vehicle/'
```

This time response is a success;

```
{
  "updated_at": "2017-08-25T12:21:26.184867028+03:00",
  "plate_id": "CC555",
  "agent": {
    "uuid": "testagent1",
    "updated_at": "2017-08-25T12:21:26.184388244+03:00",
    "label": "",
    "lat": "123123123",
    "lon": "123123123",
    "gps_ts": "123123123"
  },
  "groups": null,
  "type": "SCHOOL-BUS"
}
```

A vehicle created with an agent automatically assigned to it. 


The API or the documentation assumes that you've already created an agent.
So far the issue here is; you can not create vehicle(s) by only POSTing `plate_id` and `type` without creating at least one **agent**.

**PS:** Seems like you've tested the issue on an environment that already has an agent.

**Comment by cad** [comment] 2017-08-25 13:30
@drac it indeed turns out to be a bug. Thank you very much for going the extra mile and testing it yourself 👍.

I have included the fix and the test case for preventing regression of the bug again in the future.
This issue will close itself when the fix gets merged to the master.

**Closed as completed** 2017-08-25 13:59 UTC
Labels: bug
